package config

const GO_STARTER_TIME = "2006-01-02 15:04:05"

// DATABASE
const (
	DATABASE_USERNAME = "user"
	DATABASE_PASSWORD = "gorm"
	DATABASE_HOST     = "localhost"
	DATABASE_PORT     = 9910
	DATABASE_DBNAME   = "dousheng"
)

// videos
const (
	VIDEO_NUM_PER_REFRESH     = 6
	VIDEO_INIT_NUM_PER_AUTHOR = 10
)

// OSS config
const (
	OSS_ACCESS_KEY_ID     = "OSS_ACCESS_KEY_ID"
	OSS_ACCESS_KEY_SECRET = "OSS_ACCESS_KEY_SECRET"
	OSS_BUCKET_NAME       = "OSS_BUCKET_NAME"
	OSS_ENDPOINT          = "OSS_ENDPOINT"
	CUSTOM_DOMAIN         = "CUSTOM_DOMAIN"
	OSS_VIDEO_DIR         = "OSS_VIDEO_DIR"
	PLAY_URL_PREFIX       = CUSTOM_DOMAIN + OSS_VIDEO_DIR
	COVER_URL_SUFFIX      = "?x-oss-process=video/snapshot,t_2000,m_fast"
)
